---
# tasks file for role_windows_iis

- name: Copy webpage
  win_copy:
    src: picture.txt
    dest: 'C:/inetpub/wwwroot/index.html'
  notify: w3svc-reset

- name: Restarting the web app pool
  win_iis_webapppool:
     name: "DefaultAppPool"
     state: restarted

